# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 278b5232df381161fda24b86d94a298a336b4c7c2aacb11329c31b2739529ad19cb13537ecfd3c31fdd19c1dda84ad678535cb57abaf519c685c72895e9db953

test:
  secret_key_base: 2b9591c4eaf5cdd1060604ad329e6f1d874c086022ecaa0d6de22fdb358f0454ca45699b4f790c5b6177ba97b4aaf61c56eaefe6b63c6f415386fa66361d3af0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
